# Generated by Django 3.1.3 on 2020-11-28 12:58

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('top100_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=phone_field.models.PhoneField(max_length=31),
        ),
    ]
