# Generated by Django 3.1.4 on 2020-12-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top100_app', '0002_auto_20201128_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='top100_app/static/image/albums', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='top100_app/static/image/authors', verbose_name='Image'),
        ),
    ]
