# Generated by Django 3.1.2 on 2020-12-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top100_app', '0003_auto_20201214_1845'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gender',
            new_name='Genre',
        ),
        migrations.RemoveField(
            model_name='album',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='song',
            name='gender',
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.ManyToManyField(to='top100_app.Genre'),
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.ManyToManyField(to='top100_app.Genre'),
        ),
    ]
