# Generated by Django 3.1.2 on 2020-12-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top100_app', '0004_auto_20201214_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='image',
            field=models.ImageField(blank=True, upload_to='top100_app/static/img/', verbose_name='Image'),
        ),
    ]
