# Generated by Django 3.1.2 on 2020-12-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top100_app', '0005_genre_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='image',
            field=models.ImageField(blank=True, upload_to='top100_app/static/images/genres/', verbose_name='Image'),
        ),
    ]
