# Generated by Django 3.1.2 on 2020-12-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top100_app', '0006_auto_20201215_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='description',
            field=models.CharField(default='Description', max_length=200),
        ),
    ]
