# Generated by Django 3.1.4 on 2020-12-21 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('top100_app', '0010_song_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='song',
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='top100_app.album'),
        ),
        migrations.RemoveField(
            model_name='album',
            name='author',
        ),
        migrations.AddField(
            model_name='album',
            name='author',
            field=models.ManyToManyField(to='top100_app.Author'),
        ),
        migrations.RemoveField(
            model_name='song',
            name='author',
        ),
        migrations.AddField(
            model_name='song',
            name='author',
            field=models.ManyToManyField(to='top100_app.Author'),
        ),
    ]
