# Generated by Django 3.1.4 on 2020-12-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top100_app', '0011_auto_20201221_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='top100_app/static/images/albums', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='top100_app/static/images/authors', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='image',
            field=models.ImageField(blank=True, upload_to='top100_app/static/images/genres', verbose_name='Image'),
        ),
    ]
